name: CI
on: pull_request

jobs:
  test:
    runs-on: bts-iai-runner-linux
    steps:

      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - run: pip install black pytest
        shell: bash

      - run: echo "${{ vars.COGNITO_URL }}"
        shell: bash
